### ISSUE TITLE
You'll want to remove DaemonMap from the Readme (its listed there as one of the tools)

### ISSUE THREAD

**Issue by SeanScherer** [DaemonEngine/DaemonMediaAuthoringKit#2]
Since DaemonMap is no longer used for current Unvanquished.

Or I guess, maybe you're leaving it in (the AuthoringKit) for backwards compatability for now ? 

Sorry, I'm just digging around, and thought you'd probably want to keep things up to date.

**Comment by illwieckz** [comment]
You're right, I've removed it but forgot to push the commit! 😅️

It's now done. Thanks for the report! 👍️
